version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PACKAGES_READ_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - npm-github
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - "angular-eslint"
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
