import { defineConfig, devices } from '@playwright/test';
import { OIDC_TLS_CERT_PATH } from './e2e/mocks/oidc-tls-paths';

const SSR_PORT = 4100;
const MOCK_CURATOR_PORT = 4101;
const MOCK_OIDC_PORT = 4102;

const smokeBaseUrl = process.env['SmokeBaseUrl']?.replace(/\/$/, '');

export default defineConfig({
  // E2E specs live in e2e/; smoke specs live in e2e/smoke/.
  testDir: './e2e',

  // Artifacts go here on failure (mirrors PlaywrightArtifactRecorder behaviour).
  outputDir: './playwright-artifacts',

  // Reporters: HTML report + list for CI stdout + JUnit for ADO/App Insights publishing.
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['list'],
    ['junit', { outputFile: 'playwright-results.xml' }],
  ],

  use: {
    // Default base URL points at the local SSR server; smoke tests override via project.
    baseURL: `http://localhost:${SSR_PORT}`,
    // Retain trace / screenshot / video only on failure — mirrors C# recorder.
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
    // The Node SSR server does not use HTTPS locally; the mock OIDC provider does (a self-signed
    // cert), and the browser navigates there directly during login, so this must stay true.
    ignoreHTTPSErrors: true,
  },

  projects: [
    {
      name: 'e2e',
      // All specs outside smoke/.
      testMatch: /.*\/e2e\/(?!smoke\/).*\.spec\.ts$/,
      use: { ...devices['Desktop Chrome'] },
      // Serialise to match the C# xUnit Collection behaviour (tests share state
      // via the mock server; parallel execution causes interference).
      fullyParallel: false,
      // Force a single worker so that tests from different spec files never
      // run concurrently — they would race on the shared mock server state.
      workers: 1,
    },
    {
      name: 'smoke',
      testDir: './e2e/smoke',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: smokeBaseUrl ?? `http://localhost:${SSR_PORT}`,
      },
    },
  ],

  // ── Web servers ─────────────────────────────────────────────────────────────
  // Playwright manages all three servers during the test run.  The mock Curator and mock OIDC
  // servers must both be up before the SSR server starts (SSR's warmup request hits Curator during
  // Angular bootstrap, and /bff/login performs real OIDC discovery against the mock authority on
  // first use).
  // When SmokeBaseUrl is set (post-deploy smoke against a real deployed instance),
  // skip starting any local server entirely — there is nothing to build/run locally,
  // and the post-deploy CI job never runs `npm run build` before this config loads.
  webServer: smokeBaseUrl ? undefined : [
    {
      // Mock Curator API — handles /curator/api/* routes and /_test/* control API.
      command: 'npx tsx e2e/mocks/curator-server.ts',
      port: MOCK_CURATOR_PORT,
      reuseExistingServer: !process.env['CI'],
      timeout: 30_000,
    },
    {
      // Mock OIDC provider — real discovery/authorize/token/userinfo/jwks over real HTTPS (a
      // self-signed cert generated by "npm run e2e"'s pre-step, see e2e/mocks/generate-oidc-cert.ts)
      // so authedPage fixtures perform a genuine /bff/login round trip instead of mocking
      // /bff/user. See e2e/mocks/oidc.ts.
      command: 'npx tsx e2e/mocks/oidc-server.ts',
      port: MOCK_OIDC_PORT,
      reuseExistingServer: !process.env['CI'],
      timeout: 30_000,
    },
    {
      // Node SSR + BFF server — built output (npm run build -- --configuration=ci first).
      command: 'node --import ./instrumentation.mjs dist/librarian.client/server/server.mjs',
      port: SSR_PORT,
      env: {
        PORT: String(SSR_PORT),
        // Point the BFF proxy at the mock Curator API.
        CuratorApiAddress: `http://localhost:${MOCK_CURATOR_PORT}`,
        // Use in-memory session store — no Redis required for tests.
        SessionStore: 'memory',
        NODE_ENV: 'test',
        LibrarianClientId: 'e2e-client-id',
        LibrarianClientSecret: 'e2e-secret',
        OidcAuthority: `https://localhost:${MOCK_OIDC_PORT}`,
        // Trusts the mock OIDC provider's self-signed cert for THIS process only -- src/bff/oidc.ts
        // itself carries no insecure-transport allowance; discovery there always requires HTTPS.
        NODE_EXTRA_CA_CERTS: OIDC_TLS_CERT_PATH,
        SessionSecret: 'e2e-test-secret-must-be-at-least-32-chars',
      },
      reuseExistingServer: !process.env['CI'],
      timeout: 60_000,
    },
  ],
});
