export const environment = {
  production: true,
  allowedHosts: ['*.azurewebsites.net'],
  followListPageSize: 50,
  tokenRefreshWindowMs: 60000,
  pageSizeChoices: [20, 50, 100, 200],
  libraryPollIntervalMs: 2500,
  libraryPollErrorRetryCount: 3,
  libraryPollErrorRetryDelayMs: 2000,
  librarySearchDebounceMs: 300,
  libraryManualSearchLimit: 10,
  adminEnrichmentPollIntervalMs: 2500,
  adminEnrichmentPollErrorRetryCount: 3,
  adminEnrichmentPollErrorRetryDelayMs: 2000,
};
