export const CURATOR_API_PREFIX = '/curator/api';

export const CuratorRoutes = {
  psnLink: '/psn/link',
  catalogGames: '/catalog/games',
  catalogGamesByGameId: (gameId: string): string => `/catalog/games/${gameId}`,
  catalogGamesByGameIdCollections: (gameId: string): string => `/catalog/games/${gameId}/collections`,
  catalogGenres: '/catalog/genres',
  collections: '/collections',
  collectionsByDefinitionId: (definitionId: string): string => `/collections/${definitionId}`,
  collectionsByDefinitionIdFollow: (definitionId: string): string => `/collections/${definitionId}/follow`,
  collectionsByDefinitionIdItems: (definitionId: string): string => `/collections/${definitionId}/items`,
  collectionsByDefinitionIdItemsByGameId: (definitionId: string, gameId: string): string => `/collections/${definitionId}/items/${gameId}`,
  collectionsByDefinitionIdRuns: (definitionId: string): string => `/collections/${definitionId}/runs`,
  collectionsByDefinitionIdVisibility: (definitionId: string): string => `/collections/${definitionId}/visibility`,
  collectionsFollowed: '/collections/followed',
  collectionsPreview: '/collections/preview',
  consoles: '/consoles',
  consolesByConsoleId: (consoleId: string): string => `/consoles/${consoleId}`,
  consolesByConsoleIdDeviceLink: (consoleId: string): string => `/consoles/${consoleId}/device-link`,
  consolesByConsoleIdInstalls: (consoleId: string): string => `/consoles/${consoleId}/installs`,
  consolesByConsoleIdInstallsByGameId: (consoleId: string, gameId: string): string => `/consoles/${consoleId}/installs/${gameId}`,
  devices: '/devices',
  enrichmentRuns: '/enrichment/runs',
  enrichmentRunsByRunId: (runId: string): string => `/enrichment/runs/${runId}`,
  enrichmentRunsLatest: '/enrichment/runs/latest',
  gamesByGameIdMeasuredSizes: (gameId: string): string => `/games/${gameId}/measured-sizes`,
  gamesByGameIdMeasuredSizesByPlatform: (gameId: string, platform: string): string => `/games/${gameId}/measured-sizes/${platform}`,
  identity: '/identity',
  library: '/library',
  libraryByGameIdHidden: (gameId: string): string => `/library/${gameId}/hidden`,
  libraryGenres: '/library/genres',
  libraryManual: '/library/manual',
  libraryManualByGameId: (gameId: string): string => `/library/manual/${gameId}`,
  libraryManualCandidates: '/library/manual/candidates',
  libraryRefresh: '/library/refresh',
  libraryRefreshByRunId: (runId: string): string => `/library/refresh/${runId}`,
  me: '/me',
  meActions: '/me/actions',
  meEnrichmentKeys: '/me/enrichment-keys',
  meEnrichmentKeysOpencritic: '/me/enrichment-keys/opencritic',
  meEnrichmentKeysRawg: '/me/enrichment-keys/rawg',
  meFriendRequests: '/me/friend-requests',
  meFriendRequestsByOnlineId: (onlineId: string): string => `/me/friend-requests/${onlineId}`,
  meFriendsByOnlineId: (onlineId: string): string => `/me/friends/${onlineId}`,
  meProfileLinkSites: '/me/profile-link-sites',
  meProfileLinks: '/me/profile-links',
  meProfileLinksBySiteKey: (siteKey: string): string => `/me/profile-links/${siteKey}`,
  meProfileSettings: '/me/profile-settings',
  mePsPlusRotation: '/me/ps-plus-rotation',
  mePsPlusRotationSummary: '/me/ps-plus-rotation/summary',
  mePsnPreferences: '/me/psn-preferences',
  meRefreshSchedule: '/me/refresh-schedule',
  presence: '/presence',
  publicCollectionsByShareSlug: (shareSlug: string): string => `/public/collections/${shareSlug}`,
  storageDevices: '/storage-devices',
  storageDevicesByDeviceId: (deviceId: string): string => `/storage-devices/${deviceId}`,
  storageDevicesByDeviceIdAttach: (deviceId: string): string => `/storage-devices/${deviceId}/attach`,
  storageDevicesByDeviceIdAttachByConsoleId: (deviceId: string, consoleId: string): string => `/storage-devices/${deviceId}/attach/${consoleId}`,
  storageDevicesByDeviceIdInstalls: (deviceId: string): string => `/storage-devices/${deviceId}/installs`,
  storageDevicesByDeviceIdInstallsByGameId: (deviceId: string, gameId: string): string => `/storage-devices/${deviceId}/installs/${gameId}`,
  trophiesSummary: '/trophies/summary',
  usersBySubCollections: (sub: string): string => `/users/${sub}/collections`,
  usersBySubFollow: (sub: string): string => `/users/${sub}/follow`,
  usersBySubFollowers: (sub: string): string => `/users/${sub}/followers`,
  usersBySubFollowing: (sub: string): string => `/users/${sub}/following`,
  usersBySubLibrary: (sub: string): string => `/users/${sub}/library`,
  usersBySubLibraryGenres: (sub: string): string => `/users/${sub}/library/genres`,
  usersBySubProfile: (sub: string): string => `/users/${sub}/profile`,
} as const;

export const CuratorApi = {
  psnLink: `${CURATOR_API_PREFIX}${CuratorRoutes.psnLink}`,
  catalogGames: `${CURATOR_API_PREFIX}${CuratorRoutes.catalogGames}`,
  catalogGamesByGameId: (gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.catalogGamesByGameId(gameId)}`,
  catalogGamesByGameIdCollections: (gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.catalogGamesByGameIdCollections(gameId)}`,
  catalogGenres: `${CURATOR_API_PREFIX}${CuratorRoutes.catalogGenres}`,
  collections: `${CURATOR_API_PREFIX}${CuratorRoutes.collections}`,
  collectionsByDefinitionId: (definitionId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsByDefinitionId(definitionId)}`,
  collectionsByDefinitionIdFollow: (definitionId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsByDefinitionIdFollow(definitionId)}`,
  collectionsByDefinitionIdItems: (definitionId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsByDefinitionIdItems(definitionId)}`,
  collectionsByDefinitionIdItemsByGameId: (definitionId: string, gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsByDefinitionIdItemsByGameId(definitionId, gameId)}`,
  collectionsByDefinitionIdRuns: (definitionId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsByDefinitionIdRuns(definitionId)}`,
  collectionsByDefinitionIdVisibility: (definitionId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsByDefinitionIdVisibility(definitionId)}`,
  collectionsFollowed: `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsFollowed}`,
  collectionsPreview: `${CURATOR_API_PREFIX}${CuratorRoutes.collectionsPreview}`,
  consoles: `${CURATOR_API_PREFIX}${CuratorRoutes.consoles}`,
  consolesByConsoleId: (consoleId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.consolesByConsoleId(consoleId)}`,
  consolesByConsoleIdDeviceLink: (consoleId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.consolesByConsoleIdDeviceLink(consoleId)}`,
  consolesByConsoleIdInstalls: (consoleId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.consolesByConsoleIdInstalls(consoleId)}`,
  consolesByConsoleIdInstallsByGameId: (consoleId: string, gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.consolesByConsoleIdInstallsByGameId(consoleId, gameId)}`,
  devices: `${CURATOR_API_PREFIX}${CuratorRoutes.devices}`,
  enrichmentRuns: `${CURATOR_API_PREFIX}${CuratorRoutes.enrichmentRuns}`,
  enrichmentRunsByRunId: (runId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.enrichmentRunsByRunId(runId)}`,
  enrichmentRunsLatest: `${CURATOR_API_PREFIX}${CuratorRoutes.enrichmentRunsLatest}`,
  gamesByGameIdMeasuredSizes: (gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.gamesByGameIdMeasuredSizes(gameId)}`,
  gamesByGameIdMeasuredSizesByPlatform: (gameId: string, platform: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.gamesByGameIdMeasuredSizesByPlatform(gameId, platform)}`,
  identity: `${CURATOR_API_PREFIX}${CuratorRoutes.identity}`,
  library: `${CURATOR_API_PREFIX}${CuratorRoutes.library}`,
  libraryByGameIdHidden: (gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.libraryByGameIdHidden(gameId)}`,
  libraryGenres: `${CURATOR_API_PREFIX}${CuratorRoutes.libraryGenres}`,
  libraryManual: `${CURATOR_API_PREFIX}${CuratorRoutes.libraryManual}`,
  libraryManualByGameId: (gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.libraryManualByGameId(gameId)}`,
  libraryManualCandidates: `${CURATOR_API_PREFIX}${CuratorRoutes.libraryManualCandidates}`,
  libraryRefresh: `${CURATOR_API_PREFIX}${CuratorRoutes.libraryRefresh}`,
  libraryRefreshByRunId: (runId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.libraryRefreshByRunId(runId)}`,
  me: `${CURATOR_API_PREFIX}${CuratorRoutes.me}`,
  meActions: `${CURATOR_API_PREFIX}${CuratorRoutes.meActions}`,
  meEnrichmentKeys: `${CURATOR_API_PREFIX}${CuratorRoutes.meEnrichmentKeys}`,
  meEnrichmentKeysOpencritic: `${CURATOR_API_PREFIX}${CuratorRoutes.meEnrichmentKeysOpencritic}`,
  meEnrichmentKeysRawg: `${CURATOR_API_PREFIX}${CuratorRoutes.meEnrichmentKeysRawg}`,
  meFriendRequests: `${CURATOR_API_PREFIX}${CuratorRoutes.meFriendRequests}`,
  meFriendRequestsByOnlineId: (onlineId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.meFriendRequestsByOnlineId(onlineId)}`,
  meFriendsByOnlineId: (onlineId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.meFriendsByOnlineId(onlineId)}`,
  meProfileLinkSites: `${CURATOR_API_PREFIX}${CuratorRoutes.meProfileLinkSites}`,
  meProfileLinks: `${CURATOR_API_PREFIX}${CuratorRoutes.meProfileLinks}`,
  meProfileLinksBySiteKey: (siteKey: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.meProfileLinksBySiteKey(siteKey)}`,
  meProfileSettings: `${CURATOR_API_PREFIX}${CuratorRoutes.meProfileSettings}`,
  mePsPlusRotation: `${CURATOR_API_PREFIX}${CuratorRoutes.mePsPlusRotation}`,
  mePsPlusRotationSummary: `${CURATOR_API_PREFIX}${CuratorRoutes.mePsPlusRotationSummary}`,
  mePsnPreferences: `${CURATOR_API_PREFIX}${CuratorRoutes.mePsnPreferences}`,
  meRefreshSchedule: `${CURATOR_API_PREFIX}${CuratorRoutes.meRefreshSchedule}`,
  presence: `${CURATOR_API_PREFIX}${CuratorRoutes.presence}`,
  publicCollectionsByShareSlug: (shareSlug: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.publicCollectionsByShareSlug(shareSlug)}`,
  storageDevices: `${CURATOR_API_PREFIX}${CuratorRoutes.storageDevices}`,
  storageDevicesByDeviceId: (deviceId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.storageDevicesByDeviceId(deviceId)}`,
  storageDevicesByDeviceIdAttach: (deviceId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.storageDevicesByDeviceIdAttach(deviceId)}`,
  storageDevicesByDeviceIdAttachByConsoleId: (deviceId: string, consoleId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.storageDevicesByDeviceIdAttachByConsoleId(deviceId, consoleId)}`,
  storageDevicesByDeviceIdInstalls: (deviceId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.storageDevicesByDeviceIdInstalls(deviceId)}`,
  storageDevicesByDeviceIdInstallsByGameId: (deviceId: string, gameId: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.storageDevicesByDeviceIdInstallsByGameId(deviceId, gameId)}`,
  trophiesSummary: `${CURATOR_API_PREFIX}${CuratorRoutes.trophiesSummary}`,
  usersBySubCollections: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubCollections(sub)}`,
  usersBySubFollow: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubFollow(sub)}`,
  usersBySubFollowers: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubFollowers(sub)}`,
  usersBySubFollowing: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubFollowing(sub)}`,
  usersBySubLibrary: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubLibrary(sub)}`,
  usersBySubLibraryGenres: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubLibraryGenres(sub)}`,
  usersBySubProfile: (sub: string): string => `${CURATOR_API_PREFIX}${CuratorRoutes.usersBySubProfile(sub)}`,
} as const;

export const CuratorQueryParams = {
  q: 'q',
  genre: 'genre',
  sort: 'sort',
  sortDir: 'sortDir',
  limit: 'limit',
  offset: 'offset',
  hidden: 'hidden',
  franchise: 'franchise',
  aaaTier: 'aaaTier',
  excludeOwned: 'excludeOwned',
  kind: 'kind',
  includeStore: 'includeStore',
} as const;
