import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  { path: '', renderMode: RenderMode.Server },
  { path: 'psn', renderMode: RenderMode.Client },
  { path: 'catalog', renderMode: RenderMode.Client },
  { path: 'collections', renderMode: RenderMode.Client },
  { path: 'collections/d/:definitionId', renderMode: RenderMode.Client },
  { path: 'collections/:sub', renderMode: RenderMode.Client },
  { path: 'consoles', renderMode: RenderMode.Client },
  { path: 'c/:slug', renderMode: RenderMode.Client },
  { path: 'library', renderMode: RenderMode.Client },
  { path: 'library/:sub', renderMode: RenderMode.Client },
  { path: 'profile', renderMode: RenderMode.Client },
  { path: 'profile/followers', renderMode: RenderMode.Client },
  { path: 'profile/following', renderMode: RenderMode.Client },
  { path: 'profile/settings', renderMode: RenderMode.Client },
  { path: 'u/:sub', renderMode: RenderMode.Client },
  { path: 'u/:sub/followers', renderMode: RenderMode.Client },
  { path: 'u/:sub/following', renderMode: RenderMode.Client },
  { path: 'admin/enrichment', renderMode: RenderMode.Client },
  { path: 'faq', renderMode: RenderMode.Server },
  { path: 'privacy', renderMode: RenderMode.Server },
  { path: '**', renderMode: RenderMode.Server },
];
